
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gateway-kusk-io-v1alpha1-api
  failurePolicy: Fail
  name: mapi.kb.io
  rules:
  - apiGroups:
    - gateway.kusk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gateway-kusk-io-v1alpha1-envoyfleet
  failurePolicy: Fail
  name: menvoyfleet.kb.io
  rules:
  - apiGroups:
    - gateway.kusk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - envoyfleet
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gateway-kusk-io-v1alpha1-staticroute
  failurePolicy: Fail
  name: mstaticroute.kb.io
  rules:
  - apiGroups:
    - gateway.kusk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - staticroutes
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-kusk-io-v1alpha1-api
  failurePolicy: Fail
  name: vapi.kb.io
  rules:
  - apiGroups:
    - gateway.kusk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-kusk-io-v1alpha1-envoyfleet
  failurePolicy: Fail
  name: venvoyfleet.kb.io
  rules:
  - apiGroups:
    - gateway.kusk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - envoyfleet
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-kusk-io-v1alpha1-staticroute
  failurePolicy: Fail
  name: vstaticroute.kb.io
  rules:
  - apiGroups:
    - gateway.kusk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - staticroutes
  sideEffects: None
